version: "2"

networks:
  proxy:
    external: true
  internal:
    external: false

services:
  eve:
    build: .
    restart: always
    ports:
      - "3001:3001"
    labels:
      - traefik.backend=eve
      - traefik.frontend.rule=Host:leonerath.de,www.leonerath.de,erath.dev,wwww.erath.dev;PathPrefix:/api/eve
      - traefik.docker.network=proxy
      - traefik.port=3001
      - traefik.enable=true
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - internal
      - proxy
